[project]
name = "fault-tolerant-sandboxing"
version = "0.1.0"
description = "Fault-Tolerant Sandboxing for AI Coding Agents."
requires-python = ">=3.12"
dependencies = [
  "openai>=1.40.0",
  "docker>=7.1.0",
  "PyYAML>=6.0.2",
]

[project.optional-dependencies]
dev = [
  "pytest",
]

